apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: redux-inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redux-inventory
  template:
    metadata:
      labels:
        app: redux-inventory
    spec:
      containers:
      - name: frontend
        image: localhost:5000/redux-inventory_frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
